### PR TITLE
[fix] fixed header responsiveness

### PR DESCRIPTION
**Pull request by Kira272921**
Fixed the header responsiveness

### CODE REVIEW

**Comment by Kira272921** [comment]
i'm working on the other parts as well, need some time to complete it

**Comment by kr-anurag** [comment]
> i'm working on making the other parts responsive as well, need some time to complete it

hey, a friend of mine is also working on responsiveness, so it might result in conflicts, so thank you for your contributions, but this can result into conflicts.

**Comment by Kira272921** [comment]
> hey, a friend of mine is also working on responsiveness, so it might result in conflicts, so thank you for your contributions, but this can result into conflicts.

Oh alright :(

**Comment by kr-anurag** [comment]
> > hey, a friend of mine is also working on responsiveness, so it might result in conflicts, so thank you for your contributions, but this can result into conflicts.
> 
> Oh alright :(

ah, closing the PR wasn't needed, but nvm, sorry

**Comment by Kira272921** [comment]
> ah, closing the PR wasn't needed, but nvm, sorry

no problem :D

**Pull request closed without merging**
